name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      # Build da imagem Docker usando o Dockerfile na raiz do projeto
      - name: Build Docker image
        run: docker build -t coletaai:${{ github.sha }} .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to staging
        run: echo "Deploying to Staging Environment"

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: echo "Deploying to Production Environment"
